liver: True
crd: [2000, 4000, 3000, 5000]
colors:
  - '#914d22'
  - '#c61b84'
  - '#ec67a7'
  - '#edabcb'
  - '#5da6db'
  - '#8f4716'
  - '#fa8307'
  - '#b0763a'
  - '#d0110b'
  - '#f62c4f'
  - '#fed8b1'
  - '#cc7722'
  - '#929591'
  - '#E45466'
  - '#a31a2a'
gene_indexes:
  "Other_ImmuneCells":
    - 1
    - 2
    - 8
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 21
    - 22
    - 26
  "fibroblast":
    - 4
    - 5
    - 23
    - 25
  "stellate":
    - 28
    - 29
    - 30
