name: harpy
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.8
  - opencv
  - pip
  - pytorch
  - mkl=2024.0.0 # temp workaround, see https://github.com/pytorch/pytorch/issues/123097
  - rasterio==1.3.2
  - fsspec=2023.6.0
  - pip:
      - basicpy==1.0.0
      - jax==0.4.6
      - jaxlib==0.4.6
      - ipython
      - ipykernel