name: napari-spongepy
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pytorch=1.13
  # enable for NVIDIA GPUs
  # - cudatoolkit=11.3
  - napari
  - pandas==1.4.2
  - numpy==1.21.6
  - scikit-image==0.19.2
  - seaborn==0.11.2
  - matplotlib==3.5.2
  - scipy==1.8.0
  - jupyterlab==3.4.0
  - ipywidgets==7.7.0
  - anndata==0.8.0
  - tqdm==4.64.0
  - opencv==4.5.5
  - modestimage==0.2
  - widgetsnbextension==3.6.0
  # scanpy
  - scanpy==1.9.1
  - python-igraph
  - leidenalg
  # dev tools
  - pre-commit
  - tox
  - mypy
  - pip
  - pip:
    - squidpy==1.2.0
    - cellpose==2.0.5
    - git+https://github.com/biomicrodev/pybasic.git@e4c48496ddceb0041878c29f75dc4ef304f38b09
