name: napari-sparrow
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel=6.9.1
  - pytorch=1.12
  # disable for non-CUDA GPUs
  - cudatoolkit=11.3
  - napari=0.4.16
  - pandas==1.4.2
  - numpy==1.21.6
  - scikit-image==0.19.2
  - seaborn==0.11.2
  - matplotlib==3.5.2
  - scipy==1.8.0
  - jupyterlab==3.4.0
  - ipywidgets==7.7.0
  - anndata==0.9.1
  - tqdm==4.64.0
  - opencv==4.5.5
  - modestimage==0.2
  - widgetsnbextension==3.6.0
  # polygons
  - geopandas==0.12.2
  - rasterio==1.3.2
  # scanpy
  - scanpy==1.9.1
  - python-igraph
  # dev tools
  - pre-commit
  - pytest
  - tox
  - mypy
  - pip
  - pip:
    - squidpy==1.2.0
    - cellpose==2.0.5
    - basicpy==1.0.0
    - nbmake==1.3.4
    - pytest-xdist==2.5.0
    - spatialdata==0.0.9
    - napari-spatialdata==0.2.4
    - aicsimageio==4.9.4
    - multiscale-spatial-image==0.11.2
    - voronoi-diagram-for-polygons==0.1.6 # https://github.com/longavailable/voronoi-diagram-for-polygons/issues/6
    - black==23.1.0
    - hydra-core==1.2.0
    - leidenalg==0.9.1
    - shapely==2.0.1
    - submitit==1.4.5
    