name: harpy
channels:
  - pytorch
  - conda-forge
  - conda
  - nvidia
  - defaults
dependencies:
  - python=3.10.8
  - opencv
  - pip
  - fsspec=2023.6.0
  - pip:
      - basicpy==1.0.0
      - torch
      - cellpose
      - jax==0.4.6
      - jaxlib==0.4.6
      - ipython
      - ipykernel
