[build-system]
requires = ["setuptools>=42.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
minversion = 6.0
# show extra info for all except passes, low verbosity, auto parallel, no warnings and run tests in package
addopts = "-ra -q -n=auto --disable-warnings --pyargs napari_spongepy"
testpaths = [
    # notebook paths for --nbmake option
    "experiments/script_liver_spongepy.ipynb",
    "experiments/script_plant_spongepy.ipynb",
]
