_target_: napari_spongepy.widgets._segment_widget.create_cellpose_method
min_size: 80
flow_threshold: 0.9
diameter:  50
cellprob_threshold: -4
model_type: "nuclei"
channels: [0, 0]
small_size_vis: [3000, 6000, 5000, 9000]
