_target_: napari_sparrow.widgets._segment_widget.create_cellpose_method
output_layer: "segmentation_mask"
min_size: 80
flow_threshold: 0.8
diameter:  50
cellprob_threshold: -2
model_type: "nuclei"
channels: [0, 0]
small_size_vis: null
chunks: "auto"
crop_param: null
voronoi_radius: null