data_dir: null #${paths.data_dir}/resolve/resolve_liver
dtype: tiff
image: null #${dataset.data_dir}/20272_slide1_A1-1_DAPI.tiff
coords: null #${dataset.data_dir}/20272_slide1_A1-1_results.txt
markers: null #${dataset.data_dir}/markerGeneListMartinNoLow.csv
transform_matrix: null