# path to original working directory the app was executed from
work_dir: ${hydra:runtime.cwd}

# path to data directory
data_dir: ${paths.work_dir}/data

# path to logging directory
log_dir: ${paths.work_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# default to null for all output paths
h5ad: ${paths.output_dir}/adata.h5ad
