tilingCorrection: True
crop_param: null
tile_size: 2144
tophatFiltering: True
size_tophat: 85
contrastEnhancing: True
contrast_clip: 3.5
chunksize_clahe: 10000
depth: 3000
small_size_vis: [0, 3000, 0, 3000]
