library_id: "melanoma"
nuc_size_norm: True
n_comps: 50
min_size: 500
max_size: 100000
pcs: 17
neighbors: 35
spot_size: 70
cluster_resolution: 0.8

polygon_column: ""
polygon_cmap: "magma"
polygon_alpha: 0.5
polygon_crd: ""

total_counts_column: "total_counts"
total_counts_cmap: "magma"
total_counts_alpha: 0.5
total_counts_crd: ""

distance_column: "distance"
distance_cmap: "magma"
distance_alpha: 0.5
distance_crd: ""

leiden_column: "leiden"
leiden_cmap: "magma"
leiden_alpha: 0.5
leiden_crd: ""
