name: Run Tests

on:
  push:
    branches:
      #- main
      - SC_19_github-actions
    paths:
      - 'src/napari_sparrow/**'
      - '.github/workflows/run_tests.yml'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest ] #[ubuntu-latest, macos-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true
    
    - name: Install Mamba with libmamba
      run: |
        conda install mamba -c conda-forge
        export MAMBA_ROOT_PREFIX=$(conda info --root)
        mamba config set global.libmamba true

    - name: Create and Activate Environment
      run: |
        mamba env create -f src/napari-sparrow/environment.yml
        conda activate napari-sparrow
    
    - name: Install dependencies
      run: |
        pip install -e '.[testing]'

    - name: Run pytest
      run: |
        pytest src/napari_sparrow/_tests/test_pipeline.py
        pytest src/napari_sparrow/_tests/test_widget.py
