name: Run Tests

on:
  push:
    branches:
      #- main
      - SC_19_github-actions
    paths:
      - 'src/napari_sparrow/**'
      - '.github/workflows/run_tests.yml'
      - 'environment.yml'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest ] #[ubuntu-latest, macos-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: napari-sparrow
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
  
    - name: Install dependencies
      run: |
        pip install -e '.[testing]'

    - name: Run pytest
      run: |
        pytest src/napari_sparrow/_tests/test_pipeline.py
        pytest src/napari_sparrow/_tests/test_widget.py
