name: Run tests

on:
  push:
    branches:
      - SC_19_github-actions

  pull_request:
    branches:
      - SC_19_github-actions

    paths:
      - 'src/napari_sparrow/**'
      - '.github/workflows/run_tests.yml'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  test:

    strategy:
      matrix:
        os: [ macos-latest ] #[ubuntu-latest, macos-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: napari-sparrow
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: ~/miniconda3/envs/napari-sparrow
          key: conda-env-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}
        id: cache

      - name: Update environment
        run: mamba env update -n napari-sparrow -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'


      - name: Run pytest
        shell: bash -l {0}
        run: |
          mamba activate napari-sparrow
          pytest -vv src/napari_sparrow/_tests/test_pipeline.py
          pytest -vv src/napari_sparrow/_tests/test_widget.py
