name: Run Tests

on:
  push:
    branches:
      #- main
      - SC_19_github-actions
    paths:
      - 'src/napari_sparrow/**'
      - '.github/workflows/run_tests.yml'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest ] #[ubuntu-latest, macos-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # First, we set up a basic Conda to be able to modify it
    - name: Setup Basic Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}

      # these libraries enable testing on Qt on linux
    - uses: tlambert03/setup-qt-libs@v1

    # strategy borrowed from vispy for installing opengl libs on windows
    - name: Install Windows OpenGL
      if: runner.os == 'Windows'
      run: |
        git clone --depth 1 https://github.com/pyvista/gl-ci-helpers.git
        powershell gl-ci-helpers/appveyor/install_opengl.ps1

    # Now we set up libmamba for conda
    - name: Install libmamba
      run: |
        conda update -n base conda
        conda install -n base conda-libmamba-solver python=${{ matrix.python-version }}
        conda config --set solver libmamba

    - name: Check libmamba solver
      run: |
        conda config --show | grep solver

    - name: Create, activate environment, and install dependencies
      shell: bash -l {0}
      run: |
        conda env create -f environment.yml
        conda activate napari-sparrow
        pip install -e '.[testing]'

    - name: Run pytest
      run: |
        pytest src/napari_sparrow/_tests/test_pipeline.py
        pytest src/napari_sparrow/_tests/test_widget.py
