name: Run Tests

on:
  push:
    branches:
      - SC_18_integration_testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        auto-activate-base: true

    - name: Install Mamba
      shell: bash -l {0}
      run: |
        conda install mamba -c conda-forge

    - name: Create and activate environment with Mamba
      shell: bash -l {0}
      run: |
        mamba env create -f environment_test.yml
        conda activate some_test

    #- name: Run tests
    #  shell: bash -l {0}
    #  run: pytest -v src/napari_sparrow/_tests/test_pipeline.py  # Adjust path if necessary

    #- name: Cleanup test results
    #  shell: bash -l {0}
    #  run: rm -rf src/napari_sparrow/_tests/test_data/*

